rest login
sharpbunny/emergencyTag pull request #82
Opened 2017-04-28 15:28 UTC by frederic34

2017-04-29 08:15 UTC, viasisco requested changes

2017-04-29 08:15 UTC, viasisco commented on app/src/main/java/fr/sharpbunny/emergencytag/HttpHandler.java
> +    // TAG is used in log to identify origin of log
Use a true javadoc syntax

2017-04-29 08:15 UTC, viasisco commented on app/src/main/java/fr/sharpbunny/emergencytag/HttpHandler.java
>      public HttpHandler() {
javadoc?

2017-04-29 08:15 UTC, viasisco commented on app/src/main/java/fr/sharpbunny/emergencytag/LoginActivity.java
> +        // hack to login with rest without typing anything
no comment...

2017-04-29 08:15 UTC, viasisco commented on app/src/main/java/fr/sharpbunny/emergencytag/LoginActivity.java
> +                    // Getting JSON message
you can refer to key status. 0 if ok and 1 or more if not.

2017-04-29 16:53 UTC, frederic34 commented on app/src/main/java/fr/sharpbunny/emergencytag/LoginActivity.java
> +                    // Getting JSON message
done

2017-04-29 19:33 UTC, frederic34 commented on app/src/main/java/fr/sharpbunny/emergencytag/LoginActivity.java
> +        // hack to login with rest without typing anything
no response....

2017-05-02 06:25 UTC, Fuzhyon approved these changes

2017-05-02 06:41 UTC, merged